# Generated by Django 3.2.25 on 2025-01-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/Project/Django/srcs/media/avatars/default.jpg', upload_to='/Project/Django/srcs/media/avatars/'),
        ),
    ]
