# Generated by Django 3.2.25 on 2025-01-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='Project/Django/srcs/media/avatars/images.jpg', upload_to='Project/Django/srcs/media/avatars/'),
        ),
    ]
