volumes:
  postgres_data:

networks:
  trans_net:
    name: trans_net
    driver: bridge

services:
  web_db:
    container_name: postgresql
    image: postgres:13
    env_file:
      - .env
    expose:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trans_net
    #restart: always

  django:
    container_name: django
    build:
     context: ./Django
    volumes:
      - ./Django/djangoservice:/app
    ports:
      - "8000:8000"
    depends_on:
      - web_db
    networks:
      - trans_net
    env_file:
      - .env
    #restart: always
      
