services:
  user_db:
    image: postgres:13
    container_name: user_db
    env_file:
      - .env
    networks:
      - webnet
    expose:
      - 5432
    environment:
      - POSTGRES_DB=users

  users:
    build:
     context: ./Django
    volumes:
      - ./Django/srcs:/app
    networks:
      - webnet
    ports:
      - "8000:8000"
    depends_on:
      - user_db
    env_file:
      - .env
    environment:
      - DB_HOST=user_db
      - POSTGRES_DB=users


  friend_db:
    image: postgres:13
    container_name: friend_db
    env_file:
      - .env
    networks:
      - webnet
    expose:
      - 5432
    environment:
      - POSTGRES_DB=friends

  friend:
    build:
      context: ./Friend
    volumes:
      - ./Friend/srcs:/app
    networks:
      - webnet
    ports:
      - "8001:8000"
    depends_on:
      - friend_db
    env_file:
      - .env
    environment:
      - DB_HOST=friend_db
      - POSTGRES_DB=friends




networks:
  webnet:
    driver: bridge
