services:
  db:
    image: postgres:13
    env_file:
      - .env
    networks:
      - webnet
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
     context: ./Django
    volumes:
      - ./Django/djangoservice:/app
    networks:
      - webnet
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
      
networks:
  webnet:
    driver: bridge

volumes:
  postgres_data:
